tap_code is added on upstream
tmk_core/common/action.h
linker error is occured: undefined reference to tap_code
to workaround it use (un)register_code instead.